_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 2d4bb57e-0076-41fc-a296-21a808db14af
name: Mod4-Exam
mail: tirupati.singh@innoraft.com
slogan: ''
page:
  403: /node/41
  404: /node/42
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
